-- Metta platform — initial schema (MySQL 8+).
-- Conventions: VARCHAR(64) primary keys generated by lib/ids.js (prefix_random),
-- timestamps are ISO-8601 UTC strings, calendar dates are YYYY-MM-DD,
-- booleans are TINYINT 0/1, JSON columns are text validated by the application.
-- Tables use utf8mb4_bin (exact comparisons and ordering, as the app expects);
-- e-mail columns compare case-insensitively. Tables whose lists need the
-- insertion order as a tie-breaker have an invisible AUTO_INCREMENT `seq`.

SET FOREIGN_KEY_CHECKS = 0;

-- ---------------------------------------------------------------- accounts

CREATE TABLE clients (
  id             VARCHAR(64) NOT NULL,
  name           TEXT NOT NULL,
  legal_name     TEXT,
  document       VARCHAR(64),
  contact_name   TEXT,
  contact_email  VARCHAR(320),
  contact_phone  VARCHAR(64),
  status         VARCHAR(32) NOT NULL DEFAULT 'active' CHECK (status IN ('active','paused','archived')),
  internal_notes MEDIUMTEXT,
  created_by     VARCHAR(64),
  created_at     VARCHAR(32) NOT NULL,
  updated_at     VARCHAR(32) NOT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

-- (role = 'client') <=> client_id IS NOT NULL is enforced by the application:
-- MySQL does not allow CHECK constraints on a column with ON DELETE CASCADE.
CREATE TABLE users (
  id            VARCHAR(64) NOT NULL,
  email         VARCHAR(254) COLLATE utf8mb4_0900_as_ci NOT NULL,
  name          TEXT NOT NULL,
  role          VARCHAR(32) NOT NULL CHECK (role IN ('admin','manager','designer','finance','client')),
  client_id     VARCHAR(64),
  password_hash VARCHAR(255),
  status        VARCHAR(32) NOT NULL DEFAULT 'invited',
  job_title     TEXT,
  phone         VARCHAR(64),
  notify_email  TINYINT NOT NULL DEFAULT 1,
  created_by    VARCHAR(64),
  created_at    VARCHAR(32) NOT NULL,
  updated_at    VARCHAR(32) NOT NULL,
  last_login_at VARCHAR(32),
  PRIMARY KEY (id),
  UNIQUE KEY users_email (email),
  KEY users_client (client_id),
  CONSTRAINT users_status_check CHECK (status IN ('invited','active','disabled')),
  CONSTRAINT users_client_fk FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE sessions (
  id           VARCHAR(64) NOT NULL,
  token_hash   VARCHAR(64) NOT NULL,
  user_id      VARCHAR(64) NOT NULL,
  created_at   VARCHAR(32) NOT NULL,
  last_seen_at VARCHAR(32) NOT NULL,
  expires_at   VARCHAR(32) NOT NULL,
  revoked_at   VARCHAR(32),
  ip           VARCHAR(64),
  user_agent   VARCHAR(512),
  PRIMARY KEY (id),
  UNIQUE KEY sessions_token (token_hash),
  KEY sessions_user (user_id),
  CONSTRAINT sessions_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

-- One-time tokens for invitations and password resets (only the hash is stored).
CREATE TABLE auth_tokens (
  token_hash VARCHAR(64) NOT NULL,
  user_id    VARCHAR(64) NOT NULL,
  purpose    VARCHAR(32) NOT NULL,
  created_by VARCHAR(64),
  created_at VARCHAR(32) NOT NULL,
  expires_at VARCHAR(32) NOT NULL,
  used_at    VARCHAR(32),
  PRIMARY KEY (token_hash),
  KEY auth_tokens_user (user_id),
  CONSTRAINT auth_tokens_purpose_check CHECK (purpose IN ('invite','reset')),
  CONSTRAINT auth_tokens_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE login_attempts (
  id         BIGINT NOT NULL AUTO_INCREMENT,
  email      VARCHAR(254) COLLATE utf8mb4_0900_as_ci NOT NULL,
  ip         VARCHAR(64),
  success    TINYINT NOT NULL,
  created_at VARCHAR(32) NOT NULL,
  PRIMARY KEY (id),
  KEY login_attempts_lookup (email, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

-- Managers (and optionally other staff) see only the clients listed here.
CREATE TABLE staff_client_access (
  user_id    VARCHAR(64) NOT NULL,
  client_id  VARCHAR(64) NOT NULL,
  granted_by VARCHAR(64),
  granted_at VARCHAR(32) NOT NULL,
  PRIMARY KEY (user_id, client_id),
  KEY staff_client_access_client (client_id),
  CONSTRAINT staff_client_access_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT staff_client_access_client_fk FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE brands (
  id                    VARCHAR(64) NOT NULL,
  client_id             VARCHAR(64) NOT NULL,
  name                  TEXT NOT NULL,
  slug                  VARCHAR(191) NOT NULL,
  description           MEDIUMTEXT,
  usage_guidelines      MEDIUMTEXT,
  typography_guidelines MEDIUMTEXT,
  internal_notes        MEDIUMTEXT,
  status                VARCHAR(32) NOT NULL DEFAULT 'active' CHECK (status IN ('active','archived')),
  created_by            VARCHAR(64),
  created_at            VARCHAR(32) NOT NULL,
  updated_at            VARCHAR(32) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY brands_client_slug (client_id, slug),
  CONSTRAINT brands_client_fk FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

-- ------------------------------------------------------ catalog & commerce

CREATE TABLE services (
  id                 VARCHAR(64) NOT NULL,
  name               TEXT NOT NULL,
  kind               VARCHAR(32) NOT NULL CHECK (kind IN ('subscription','one_off')),
  price_cents        BIGINT NOT NULL CHECK (price_cents >= 0),
  billing_interval   VARCHAR(32) CHECK (billing_interval IN ('monthly')),
  description        MEDIUMTEXT,
  items              MEDIUMTEXT NOT NULL DEFAULT ('[]'),
  includes_editables TINYINT NOT NULL DEFAULT 0,
  active             TINYINT NOT NULL DEFAULT 1,
  sort_order         INT NOT NULL DEFAULT 0,
  created_at         VARCHAR(32) NOT NULL,
  updated_at         VARCHAR(32) NOT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE subscriptions (
  id                 VARCHAR(64) NOT NULL,
  client_id          VARCHAR(64) NOT NULL,
  service_id         VARCHAR(64) NOT NULL,
  amount_cents       BIGINT NOT NULL CHECK (amount_cents >= 0),
  status             VARCHAR(32) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','active','paused','cancelled','failed')),
  payer_email        VARCHAR(320),
  external_reference VARCHAR(191) NOT NULL,
  mp_preapproval_id  VARCHAR(191),
  checkout_url       TEXT,
  started_at         VARCHAR(32),
  next_billing_date  VARCHAR(32),
  cancelled_at       VARCHAR(32),
  failure_reason     TEXT,
  created_by         VARCHAR(64),
  created_at         VARCHAR(32) NOT NULL,
  updated_at         VARCHAR(32) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY subscriptions_external_reference (external_reference),
  UNIQUE KEY subscriptions_mp_preapproval (mp_preapproval_id),
  KEY subscriptions_client (client_id),
  KEY subscriptions_service (service_id),
  CONSTRAINT subscriptions_client_fk FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE,
  CONSTRAINT subscriptions_service_fk FOREIGN KEY (service_id) REFERENCES services(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE orders (
  id                 VARCHAR(64) NOT NULL,
  client_id          VARCHAR(64) NOT NULL,
  brand_id           VARCHAR(64),
  service_id         VARCHAR(64),
  description        TEXT NOT NULL,
  amount_cents       BIGINT NOT NULL CHECK (amount_cents > 0),
  status             VARCHAR(32) NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','pending_payment','paid','failed','cancelled','refunded')),
  due_date           VARCHAR(32),
  external_reference VARCHAR(191) NOT NULL,
  mp_preference_id   VARCHAR(191),
  checkout_url       TEXT,
  paid_at            VARCHAR(32),
  failure_reason     TEXT,
  created_by         VARCHAR(64),
  created_at         VARCHAR(32) NOT NULL,
  updated_at         VARCHAR(32) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY orders_external_reference (external_reference),
  KEY orders_client (client_id),
  KEY orders_brand (brand_id),
  KEY orders_service (service_id),
  CONSTRAINT orders_client_fk FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE,
  CONSTRAINT orders_brand_fk FOREIGN KEY (brand_id) REFERENCES brands(id) ON DELETE SET NULL,
  CONSTRAINT orders_service_fk FOREIGN KEY (service_id) REFERENCES services(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE payments (
  id                  VARCHAR(64) NOT NULL,
  provider            VARCHAR(64) NOT NULL DEFAULT 'mercadopago',
  provider_payment_id VARCHAR(191) NOT NULL,
  order_id            VARCHAR(64),
  subscription_id     VARCHAR(64),
  client_id           VARCHAR(64),
  status              VARCHAR(64) NOT NULL,
  status_detail       TEXT,
  amount_cents        BIGINT,
  method              VARCHAR(64),
  paid_at             VARCHAR(32),
  raw                 MEDIUMTEXT,
  created_at          VARCHAR(32) NOT NULL,
  updated_at          VARCHAR(32) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY payments_provider_payment (provider, provider_payment_id),
  KEY payments_order (order_id),
  KEY payments_subscription (subscription_id),
  KEY payments_client (client_id),
  CONSTRAINT payments_order_fk FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE SET NULL,
  CONSTRAINT payments_subscription_fk FOREIGN KEY (subscription_id) REFERENCES subscriptions(id) ON DELETE SET NULL,
  CONSTRAINT payments_client_fk FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE webhook_events (
  id              VARCHAR(64) NOT NULL,
  seq             BIGINT NOT NULL AUTO_INCREMENT INVISIBLE,
  provider        VARCHAR(64) NOT NULL,
  request_id      VARCHAR(191),
  topic           VARCHAR(191),
  resource_id     VARCHAR(191),
  signature_valid TINYINT NOT NULL,
  payload         MEDIUMTEXT,
  received_at     VARCHAR(32) NOT NULL,
  processed_at    VARCHAR(32),
  error           TEXT,
  PRIMARY KEY (id),
  UNIQUE KEY webhook_events_seq (seq),
  UNIQUE KEY webhook_events_request (provider, request_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

-- ------------------------------------------------------- projects & tasks

CREATE TABLE projects (
  id                 VARCHAR(64) NOT NULL,
  brand_id           VARCHAR(64) NOT NULL,
  service_id         VARCHAR(64),
  subscription_id    VARCHAR(64),
  name               TEXT NOT NULL,
  description        MEDIUMTEXT,
  status             VARCHAR(32) NOT NULL DEFAULT 'planning' CHECK (status IN ('planning','in_progress','in_review','delivered','paused','archived')),
  includes_editables TINYINT NOT NULL DEFAULT 0,
  start_date         VARCHAR(32),
  due_date           VARCHAR(32),
  delivered_at       VARCHAR(32),
  internal_notes     MEDIUMTEXT,
  created_by         VARCHAR(64),
  created_at         VARCHAR(32) NOT NULL,
  updated_at         VARCHAR(32) NOT NULL,
  PRIMARY KEY (id),
  KEY projects_brand (brand_id),
  KEY projects_service (service_id),
  KEY projects_subscription (subscription_id),
  CONSTRAINT projects_brand_fk FOREIGN KEY (brand_id) REFERENCES brands(id) ON DELETE CASCADE,
  CONSTRAINT projects_service_fk FOREIGN KEY (service_id) REFERENCES services(id),
  CONSTRAINT projects_subscription_fk FOREIGN KEY (subscription_id) REFERENCES subscriptions(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE project_members (
  project_id VARCHAR(64) NOT NULL,
  user_id    VARCHAR(64) NOT NULL,
  role       VARCHAR(32) NOT NULL DEFAULT 'designer' CHECK (role IN ('lead','designer','editor')),
  added_by   VARCHAR(64),
  added_at   VARCHAR(32) NOT NULL,
  PRIMARY KEY (project_id, user_id),
  KEY project_members_user (user_id),
  CONSTRAINT project_members_project_fk FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
  CONSTRAINT project_members_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE tasks (
  id           VARCHAR(64) NOT NULL,
  project_id   VARCHAR(64) NOT NULL,
  material_id  VARCHAR(64),
  title        TEXT NOT NULL,
  description  MEDIUMTEXT,
  assignee_id  VARCHAR(64),
  status       VARCHAR(32) NOT NULL DEFAULT 'todo' CHECK (status IN ('todo','doing','review','done')),
  due_date     VARCHAR(32),
  sort_order   INT NOT NULL DEFAULT 0,
  created_by   VARCHAR(64),
  created_at   VARCHAR(32) NOT NULL,
  updated_at   VARCHAR(32) NOT NULL,
  completed_at VARCHAR(32),
  PRIMARY KEY (id),
  KEY tasks_project (project_id),
  KEY tasks_assignee (assignee_id),
  KEY tasks_material (material_id),
  CONSTRAINT tasks_project_fk FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
  CONSTRAINT tasks_material_fk FOREIGN KEY (material_id) REFERENCES materials(id) ON DELETE SET NULL,
  CONSTRAINT tasks_assignee_fk FOREIGN KEY (assignee_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE campaigns (
  id          VARCHAR(64) NOT NULL,
  brand_id    VARCHAR(64) NOT NULL,
  project_id  VARCHAR(64),
  name        TEXT NOT NULL,
  description MEDIUMTEXT,
  start_date  VARCHAR(32),
  end_date    VARCHAR(32),
  created_by  VARCHAR(64),
  created_at  VARCHAR(32) NOT NULL,
  updated_at  VARCHAR(32) NOT NULL,
  PRIMARY KEY (id),
  KEY campaigns_brand (brand_id),
  KEY campaigns_project (project_id),
  CONSTRAINT campaigns_brand_fk FOREIGN KEY (brand_id) REFERENCES brands(id) ON DELETE CASCADE,
  CONSTRAINT campaigns_project_fk FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

-- ------------------------------------------------------------- materials

-- area drives the first ZIP folder: identity -> "Identidade visual",
-- content -> "Conteúdo", other -> "Materiais". folder is the second level.
CREATE TABLE categories (
  id          VARCHAR(64) NOT NULL,
  slug        VARCHAR(191) NOT NULL,
  name        TEXT NOT NULL,
  area        VARCHAR(32) NOT NULL CHECK (area IN ('identity','content','other')),
  folder      TEXT NOT NULL,
  sort_order  INT NOT NULL DEFAULT 0,
  is_system   TINYINT NOT NULL DEFAULT 0,
  archived_at VARCHAR(32),
  created_by  VARCHAR(64),
  created_at  VARCHAR(32) NOT NULL,
  updated_at  VARCHAR(32) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY categories_slug (slug)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

-- Files a staff member uploaded but has not attached to a material yet.
-- Always private to the uploader (and admins).
CREATE TABLE uploads (
  id            VARCHAR(64) NOT NULL,
  user_id       VARCHAR(64) NOT NULL,
  original_name TEXT NOT NULL,
  ext           VARCHAR(32) NOT NULL,
  mime          VARCHAR(255) NOT NULL,
  size_bytes    BIGINT NOT NULL,
  sha256        VARCHAR(64) NOT NULL,
  storage_key   VARCHAR(255) NOT NULL,
  media_kind    VARCHAR(32) NOT NULL,
  width         INT,
  height        INT,
  duration_ms   BIGINT,
  status        VARCHAR(32) NOT NULL DEFAULT 'uploaded' CHECK (status IN ('uploaded','attached','discarded')),
  created_at    VARCHAR(32) NOT NULL,
  attached_at   VARCHAR(32),
  PRIMARY KEY (id),
  KEY uploads_user (user_id, status),
  CONSTRAINT uploads_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

-- A material is either a delivered asset (logo, manual, presentation…) or a
-- content post (kind = 'post', with a post_details row). visibility controls
-- what the client can see; approval is tracked per version.
-- primary_slot enforces one primary material per brand/category/variant
-- among non-archived rows (NULL for every other row).
CREATE TABLE materials (
  id                  VARCHAR(64) NOT NULL,
  kind                VARCHAR(32) NOT NULL CHECK (kind IN ('asset','post')),
  brand_id            VARCHAR(64) NOT NULL,
  project_id          VARCHAR(64),
  category_id         VARCHAR(64) NOT NULL,
  title               TEXT NOT NULL,
  description         MEDIUMTEXT,
  tags                MEDIUMTEXT NOT NULL DEFAULT ('[]'),
  owner_id            VARCHAR(64),
  variant             VARCHAR(32) CHECK (variant IS NULL OR variant IN ('principal','secundaria','simbolo','clara','escura','monocromatica')),
  preview_bg          VARCHAR(32) NOT NULL DEFAULT 'auto' CHECK (preview_bg IN ('auto','light','dark','checker')),
  is_primary          TINYINT NOT NULL DEFAULT 0,
  sort_order          INT NOT NULL DEFAULT 0,
  visibility          VARCHAR(32) NOT NULL DEFAULT 'draft' CHECK (visibility IN ('draft','internal_review','released')),
  download_enabled    TINYINT NOT NULL DEFAULT 1,
  editable_included   TINYINT NOT NULL DEFAULT 0,
  requires_approval   TINYINT NOT NULL DEFAULT 1,
  approval_status     VARCHAR(32) NOT NULL DEFAULT 'none' CHECK (approval_status IN ('none','pending','changes_requested','approved')),
  current_version_id  VARCHAR(64),
  released_version_id VARCHAR(64),
  approved_version_id VARCHAR(64),
  due_date            VARCHAR(32),
  internal_notes      MEDIUMTEXT,
  released_at         VARCHAR(32),
  released_by         VARCHAR(64),
  delivered_at        VARCHAR(32),
  archived_at         VARCHAR(32),
  archived_by         VARCHAR(64),
  created_by          VARCHAR(64),
  created_at          VARCHAR(32) NOT NULL,
  updated_at          VARCHAR(32) NOT NULL,
  primary_slot        VARCHAR(200) GENERATED ALWAYS AS (
                        CASE WHEN is_primary = 1 AND archived_at IS NULL
                             THEN CONCAT(brand_id, '|', category_id, '|', COALESCE(variant, '')) END
                      ) VIRTUAL INVISIBLE,
  PRIMARY KEY (id),
  KEY materials_brand (brand_id, category_id),
  KEY materials_project (project_id),
  KEY materials_category (category_id),
  KEY materials_owner (owner_id),
  KEY materials_visibility (visibility, approval_status),
  UNIQUE KEY materials_one_primary (primary_slot),
  CONSTRAINT materials_brand_fk FOREIGN KEY (brand_id) REFERENCES brands(id) ON DELETE CASCADE,
  CONSTRAINT materials_project_fk FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE SET NULL,
  CONSTRAINT materials_category_fk FOREIGN KEY (category_id) REFERENCES categories(id),
  CONSTRAINT materials_owner_fk FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE post_details (
  material_id        VARCHAR(64) NOT NULL,
  campaign_id        VARCHAR(64),
  network            VARCHAR(32) NOT NULL CHECK (network IN ('instagram','facebook','linkedin','tiktok','youtube','x','pinterest','whatsapp','outro')),
  format             VARCHAR(32) NOT NULL CHECK (format IN ('estatico','carrossel','stories','reels','video','outro')),
  planned_date       VARCHAR(32),
  planned_time       VARCHAR(16),
  publication_status VARCHAR(32) NOT NULL DEFAULT 'not_scheduled' CHECK (publication_status IN ('not_scheduled','scheduled','published')),
  scheduled_at       VARCHAR(32),
  scheduled_by       VARCHAR(64),
  published_at       VARCHAR(32),
  published_by       VARCHAR(64),
  published_url      TEXT,
  PRIMARY KEY (material_id),
  KEY post_details_date (planned_date),
  KEY post_details_campaign (campaign_id),
  CONSTRAINT post_details_material_fk FOREIGN KEY (material_id) REFERENCES materials(id) ON DELETE CASCADE,
  CONSTRAINT post_details_campaign_fk FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE material_versions (
  id             VARCHAR(64) NOT NULL,
  material_id    VARCHAR(64) NOT NULL,
  number         INT NOT NULL,
  status         VARCHAR(32) NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','internal_review','released','changes_requested','approved','superseded')),
  caption        MEDIUMTEXT,
  hashtags       MEDIUMTEXT,
  notes          MEDIUMTEXT,
  change_summary MEDIUMTEXT,
  created_by     VARCHAR(64) NOT NULL,
  created_at     VARCHAR(32) NOT NULL,
  submitted_at   VARCHAR(32),
  released_at    VARCHAR(32),
  released_by    VARCHAR(64),
  decided_at     VARCHAR(32),
  decided_by     VARCHAR(64),
  PRIMARY KEY (id),
  UNIQUE KEY material_versions_number (material_id, number),
  KEY material_versions_creator (created_by),
  CONSTRAINT material_versions_material_fk FOREIGN KEY (material_id) REFERENCES materials(id) ON DELETE CASCADE,
  CONSTRAINT material_versions_creator_fk FOREIGN KEY (created_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

-- role: original = full-quality presented file; final = approved delivery
-- export; editable = source file (only when the service includes it);
-- cover = poster/cover image used as thumbnail (never offered as a download
-- on its own). position orders carousel slides (1..n).
CREATE TABLE material_files (
  id                 VARCHAR(64) NOT NULL,
  version_id         VARCHAR(64) NOT NULL,
  material_id        VARCHAR(64) NOT NULL,
  role               VARCHAR(32) NOT NULL CHECK (role IN ('original','final','editable','cover')),
  position           INT NOT NULL DEFAULT 1,
  original_name      TEXT NOT NULL,
  display_name       TEXT NOT NULL,
  ext                VARCHAR(32) NOT NULL,
  mime               VARCHAR(255) NOT NULL,
  size_bytes         BIGINT NOT NULL,
  sha256             VARCHAR(64) NOT NULL,
  storage_key        VARCHAR(255) NOT NULL,
  media_kind         VARCHAR(32) NOT NULL CHECK (media_kind IN ('image','vector','video','audio','pdf','font','document','archive','design','other')),
  width              INT,
  height             INT,
  duration_ms        BIGINT,
  preview_status     VARCHAR(32) NOT NULL DEFAULT 'pending' CHECK (preview_status IN ('pending','ready','unsupported','failed')),
  font_distributable TINYINT,
  created_by         VARCHAR(64),
  created_at         VARCHAR(32) NOT NULL,
  PRIMARY KEY (id),
  KEY material_files_version (version_id, role, position),
  KEY material_files_material (material_id),
  CONSTRAINT material_files_version_fk FOREIGN KEY (version_id) REFERENCES material_versions(id) ON DELETE CASCADE,
  CONSTRAINT material_files_material_fk FOREIGN KEY (material_id) REFERENCES materials(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

-- Optimised previews, generated separately from the originals.
CREATE TABLE file_renditions (
  file_id     VARCHAR(64) NOT NULL,
  kind        VARCHAR(32) NOT NULL CHECK (kind IN ('thumb','preview','poster')),
  storage_key VARCHAR(255) NOT NULL,
  mime        VARCHAR(255) NOT NULL,
  width       INT,
  height      INT,
  size_bytes  BIGINT,
  created_at  VARCHAR(32) NOT NULL,
  PRIMARY KEY (file_id, kind),
  CONSTRAINT file_renditions_file_fk FOREIGN KEY (file_id) REFERENCES material_files(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

-- usage_notes: how the color is used (the API field is `usage`).
CREATE TABLE brand_colors (
  id          VARCHAR(64) NOT NULL,
  brand_id    VARCHAR(64) NOT NULL,
  name        TEXT NOT NULL,
  hex         VARCHAR(16) NOT NULL,
  rgb         TEXT,
  cmyk        TEXT,
  pantone     TEXT,
  role        TEXT,
  usage_notes MEDIUMTEXT,
  sort_order  INT NOT NULL DEFAULT 0,
  visibility  VARCHAR(32) NOT NULL DEFAULT 'draft' CHECK (visibility IN ('draft','released')),
  created_by  VARCHAR(64),
  created_at  VARCHAR(32) NOT NULL,
  updated_at  VARCHAR(32) NOT NULL,
  PRIMARY KEY (id),
  KEY brand_colors_brand (brand_id),
  CONSTRAINT brand_colors_brand_fk FOREIGN KEY (brand_id) REFERENCES brands(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

-- distribution = 'allowed' lets clients download the font files attached
-- through material_id; 'reference_only' shows only the official source link.
-- usage_notes: how the font is used (the API field is `usage`).
CREATE TABLE brand_fonts (
  id           VARCHAR(64) NOT NULL,
  brand_id     VARCHAR(64) NOT NULL,
  family       TEXT NOT NULL,
  role         TEXT,
  weights      TEXT,
  usage_notes  MEDIUMTEXT,
  source_url   TEXT,
  license      TEXT,
  distribution VARCHAR(32) NOT NULL DEFAULT 'reference_only' CHECK (distribution IN ('allowed','reference_only')),
  material_id  VARCHAR(64),
  sort_order   INT NOT NULL DEFAULT 0,
  visibility   VARCHAR(32) NOT NULL DEFAULT 'draft' CHECK (visibility IN ('draft','released')),
  created_by   VARCHAR(64),
  created_at   VARCHAR(32) NOT NULL,
  updated_at   VARCHAR(32) NOT NULL,
  PRIMARY KEY (id),
  KEY brand_fonts_brand (brand_id),
  KEY brand_fonts_material (material_id),
  CONSTRAINT brand_fonts_brand_fk FOREIGN KEY (brand_id) REFERENCES brands(id) ON DELETE CASCADE,
  CONSTRAINT brand_fonts_material_fk FOREIGN KEY (material_id) REFERENCES materials(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE kits (
  id          VARCHAR(64) NOT NULL,
  brand_id    VARCHAR(64) NOT NULL,
  project_id  VARCHAR(64),
  name        TEXT NOT NULL,
  description MEDIUMTEXT,
  kind        VARCHAR(32) NOT NULL DEFAULT 'custom' CHECK (kind IN ('brand_kit','project_package','custom')),
  status      VARCHAR(32) NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','released','archived')),
  released_at VARCHAR(32),
  released_by VARCHAR(64),
  created_by  VARCHAR(64),
  created_at  VARCHAR(32) NOT NULL,
  updated_at  VARCHAR(32) NOT NULL,
  PRIMARY KEY (id),
  KEY kits_brand (brand_id),
  KEY kits_project (project_id),
  CONSTRAINT kits_brand_fk FOREIGN KEY (brand_id) REFERENCES brands(id) ON DELETE CASCADE,
  CONSTRAINT kits_project_fk FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE kit_items (
  kit_id      VARCHAR(64) NOT NULL,
  material_id VARCHAR(64) NOT NULL,
  sort_order  INT NOT NULL DEFAULT 0,
  seq         BIGINT NOT NULL AUTO_INCREMENT INVISIBLE,
  PRIMARY KEY (kit_id, material_id),
  UNIQUE KEY kit_items_seq (seq),
  CONSTRAINT kit_items_kit_fk FOREIGN KEY (kit_id) REFERENCES kits(id) ON DELETE CASCADE,
  CONSTRAINT kit_items_material_fk FOREIGN KEY (material_id) REFERENCES materials(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

-- --------------------------------------------------- review & approvals

CREATE TABLE comments (
  id             VARCHAR(64) NOT NULL,
  seq            BIGINT NOT NULL AUTO_INCREMENT INVISIBLE,
  material_id    VARCHAR(64) NOT NULL,
  version_id     VARCHAR(64),
  parent_id      VARCHAR(64),
  author_id      VARCHAR(64) NOT NULL,
  body           MEDIUMTEXT NOT NULL,
  visibility     VARCHAR(32) NOT NULL CHECK (visibility IN ('client','internal')),
  kind           VARCHAR(32) NOT NULL DEFAULT 'comment' CHECK (kind IN ('comment','change_request','approval_note')),
  slide_position INT,
  created_at     VARCHAR(32) NOT NULL,
  edited_at      VARCHAR(32),
  resolved_at    VARCHAR(32),
  resolved_by    VARCHAR(64),
  PRIMARY KEY (id),
  UNIQUE KEY comments_seq (seq),
  KEY comments_material (material_id, created_at),
  KEY comments_version (version_id),
  KEY comments_parent (parent_id),
  KEY comments_author (author_id),
  CONSTRAINT comments_material_fk FOREIGN KEY (material_id) REFERENCES materials(id) ON DELETE CASCADE,
  CONSTRAINT comments_version_fk FOREIGN KEY (version_id) REFERENCES material_versions(id) ON DELETE SET NULL,
  CONSTRAINT comments_parent_fk FOREIGN KEY (parent_id) REFERENCES comments(id) ON DELETE SET NULL,
  CONSTRAINT comments_author_fk FOREIGN KEY (author_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

-- Immutable decision log. A new version always requires a new decision.
CREATE TABLE approvals (
  id          VARCHAR(64) NOT NULL,
  seq         BIGINT NOT NULL AUTO_INCREMENT INVISIBLE,
  material_id VARCHAR(64) NOT NULL,
  version_id  VARCHAR(64) NOT NULL,
  decision    VARCHAR(32) NOT NULL CHECK (decision IN ('approved','changes_requested')),
  user_id     VARCHAR(64) NOT NULL,
  comment_id  VARCHAR(64),
  ip          VARCHAR(64),
  user_agent  VARCHAR(512),
  created_at  VARCHAR(32) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY approvals_seq (seq),
  KEY approvals_material (material_id, created_at),
  KEY approvals_version (version_id),
  KEY approvals_user (user_id),
  KEY approvals_comment (comment_id),
  CONSTRAINT approvals_material_fk FOREIGN KEY (material_id) REFERENCES materials(id) ON DELETE CASCADE,
  CONSTRAINT approvals_version_fk FOREIGN KEY (version_id) REFERENCES material_versions(id) ON DELETE CASCADE,
  CONSTRAINT approvals_user_fk FOREIGN KEY (user_id) REFERENCES users(id),
  CONSTRAINT approvals_comment_fk FOREIGN KEY (comment_id) REFERENCES comments(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

-- ------------------------------------------------------ delivery & downloads

CREATE TABLE releases (
  id           VARCHAR(64) NOT NULL,
  client_id    VARCHAR(64) NOT NULL,
  brand_id     VARCHAR(64) NOT NULL,
  kit_id       VARCHAR(64),
  actor_id     VARCHAR(64) NOT NULL,
  message      MEDIUMTEXT,
  notify_email TINYINT NOT NULL DEFAULT 0,
  notify_app   TINYINT NOT NULL DEFAULT 1,
  created_at   VARCHAR(32) NOT NULL,
  PRIMARY KEY (id),
  KEY releases_client (client_id, created_at),
  KEY releases_brand (brand_id),
  KEY releases_kit (kit_id),
  KEY releases_actor (actor_id),
  CONSTRAINT releases_client_fk FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE,
  CONSTRAINT releases_brand_fk FOREIGN KEY (brand_id) REFERENCES brands(id) ON DELETE CASCADE,
  CONSTRAINT releases_kit_fk FOREIGN KEY (kit_id) REFERENCES kits(id) ON DELETE SET NULL,
  CONSTRAINT releases_actor_fk FOREIGN KEY (actor_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE release_items (
  release_id       VARCHAR(64) NOT NULL,
  material_id      VARCHAR(64) NOT NULL,
  version_id       VARCHAR(64) NOT NULL,
  download_enabled TINYINT NOT NULL,
  PRIMARY KEY (release_id, material_id),
  KEY release_items_version (version_id),
  CONSTRAINT release_items_release_fk FOREIGN KEY (release_id) REFERENCES releases(id) ON DELETE CASCADE,
  CONSTRAINT release_items_material_fk FOREIGN KEY (material_id) REFERENCES materials(id) ON DELETE CASCADE,
  CONSTRAINT release_items_version_fk FOREIGN KEY (version_id) REFERENCES material_versions(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE zip_jobs (
  id              VARCHAR(64) NOT NULL,
  user_id         VARCHAR(64) NOT NULL,
  client_id       VARCHAR(64),
  brand_id        VARCHAR(64),
  scope           VARCHAR(191) NOT NULL,
  label           TEXT NOT NULL,
  filename        TEXT NOT NULL,
  status          VARCHAR(32) NOT NULL DEFAULT 'queued' CHECK (status IN ('queued','running','ready','failed','expired')),
  file_count      INT NOT NULL DEFAULT 0,
  total_bytes     BIGINT NOT NULL DEFAULT 0,
  processed_bytes BIGINT NOT NULL DEFAULT 0,
  storage_key     VARCHAR(255),
  size_bytes      BIGINT,
  error           TEXT,
  created_at      VARCHAR(32) NOT NULL,
  started_at      VARCHAR(32),
  finished_at     VARCHAR(32),
  expires_at      VARCHAR(32),
  PRIMARY KEY (id),
  KEY zip_jobs_user (user_id, created_at),
  KEY zip_jobs_client (client_id),
  KEY zip_jobs_brand (brand_id),
  CONSTRAINT zip_jobs_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT zip_jobs_client_fk FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE,
  CONSTRAINT zip_jobs_brand_fk FOREIGN KEY (brand_id) REFERENCES brands(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

-- Download history. Never used to infer approval.
CREATE TABLE download_events (
  id          VARCHAR(64) NOT NULL,
  user_id     VARCHAR(64) NOT NULL,
  client_id   VARCHAR(64),
  brand_id    VARCHAR(64),
  material_id VARCHAR(64),
  version_id  VARCHAR(64),
  file_id     VARCHAR(64),
  zip_job_id  VARCHAR(64),
  kind        VARCHAR(32) NOT NULL CHECK (kind IN ('file','zip')),
  scope       VARCHAR(191) NOT NULL,
  ip          VARCHAR(64),
  user_agent  VARCHAR(512),
  created_at  VARCHAR(32) NOT NULL,
  PRIMARY KEY (id),
  KEY download_events_client (client_id, created_at),
  KEY download_events_material (material_id),
  KEY download_events_user (user_id),
  KEY download_events_brand (brand_id),
  KEY download_events_version (version_id),
  KEY download_events_file (file_id),
  KEY download_events_zip (zip_job_id),
  CONSTRAINT download_events_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT download_events_client_fk FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE,
  CONSTRAINT download_events_brand_fk FOREIGN KEY (brand_id) REFERENCES brands(id) ON DELETE SET NULL,
  CONSTRAINT download_events_material_fk FOREIGN KEY (material_id) REFERENCES materials(id) ON DELETE SET NULL,
  CONSTRAINT download_events_version_fk FOREIGN KEY (version_id) REFERENCES material_versions(id) ON DELETE SET NULL,
  CONSTRAINT download_events_file_fk FOREIGN KEY (file_id) REFERENCES material_files(id) ON DELETE SET NULL,
  CONSTRAINT download_events_zip_fk FOREIGN KEY (zip_job_id) REFERENCES zip_jobs(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

-- --------------------------------------------------------------- briefings

CREATE TABLE briefings (
  id           VARCHAR(64) NOT NULL,
  brand_id     VARCHAR(64) NOT NULL,
  project_id   VARCHAR(64),
  title        TEXT NOT NULL,
  intro        MEDIUMTEXT,
  questions    MEDIUMTEXT NOT NULL DEFAULT ('[]'),
  answers      MEDIUMTEXT NOT NULL DEFAULT ('{}'),
  status       VARCHAR(32) NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','awaiting_client','in_progress','submitted','reviewed')),
  due_date     VARCHAR(32),
  sent_at      VARCHAR(32),
  submitted_at VARCHAR(32),
  submitted_by VARCHAR(64),
  reviewed_at  VARCHAR(32),
  reviewed_by  VARCHAR(64),
  created_by   VARCHAR(64),
  created_at   VARCHAR(32) NOT NULL,
  updated_at   VARCHAR(32) NOT NULL,
  PRIMARY KEY (id),
  KEY briefings_brand (brand_id, status),
  KEY briefings_project (project_id),
  CONSTRAINT briefings_brand_fk FOREIGN KEY (brand_id) REFERENCES brands(id) ON DELETE CASCADE,
  CONSTRAINT briefings_project_fk FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

-- ------------------------------------------------ notifications & history

CREATE TABLE notifications (
  id          VARCHAR(64) NOT NULL,
  seq         BIGINT NOT NULL AUTO_INCREMENT INVISIBLE,
  user_id     VARCHAR(64) NOT NULL,
  type        VARCHAR(191) NOT NULL,
  title       TEXT NOT NULL,
  body        MEDIUMTEXT,
  link        TEXT,
  entity_type VARCHAR(64),
  entity_id   VARCHAR(191),
  read_at     VARCHAR(32),
  created_at  VARCHAR(32) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY notifications_seq (seq),
  KEY notifications_user (user_id, read_at, created_at),
  CONSTRAINT notifications_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE email_outbox (
  id          VARCHAR(64) NOT NULL,
  seq         BIGINT NOT NULL AUTO_INCREMENT INVISIBLE,
  to_email    VARCHAR(320) NOT NULL,
  to_user_id  VARCHAR(64),
  subject     TEXT NOT NULL,
  text_body   MEDIUMTEXT NOT NULL,
  html_body   MEDIUMTEXT,
  status      VARCHAR(32) NOT NULL DEFAULT 'queued' CHECK (status IN ('queued','sent','failed','not_configured')),
  error       TEXT,
  attempts    INT NOT NULL DEFAULT 0,
  created_at  VARCHAR(32) NOT NULL,
  sent_at     VARCHAR(32),
  PRIMARY KEY (id),
  UNIQUE KEY email_outbox_seq (seq),
  KEY email_outbox_user (to_user_id),
  KEY email_outbox_status (status, created_at),
  CONSTRAINT email_outbox_user_fk FOREIGN KEY (to_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

-- Full audit trail. visibility = 'client' entries may be shown to the
-- client's own users; everything else is staff-only.
CREATE TABLE activity_log (
  id          BIGINT NOT NULL AUTO_INCREMENT,
  actor_id    VARCHAR(64),
  actor_role  VARCHAR(32),
  action      VARCHAR(191) NOT NULL,
  entity_type VARCHAR(64) NOT NULL,
  entity_id   VARCHAR(191),
  client_id   VARCHAR(64),
  brand_id    VARCHAR(64),
  project_id  VARCHAR(64),
  material_id VARCHAR(64),
  summary     TEXT NOT NULL,
  data        MEDIUMTEXT,
  visibility  VARCHAR(32) NOT NULL DEFAULT 'internal' CHECK (visibility IN ('internal','client')),
  ip          VARCHAR(64),
  created_at  VARCHAR(32) NOT NULL,
  PRIMARY KEY (id),
  KEY activity_client (client_id, created_at),
  KEY activity_material (material_id, created_at),
  KEY activity_entity (entity_type, entity_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

-- Values are JSON text (lib/settings.js).
CREATE TABLE settings (
  name       VARCHAR(191) NOT NULL,
  value      MEDIUMTEXT,
  updated_by VARCHAR(64),
  updated_at VARCHAR(32) NOT NULL,
  PRIMARY KEY (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

SET FOREIGN_KEY_CHECKS = 1;
