-- Metta platform — initial schema.
-- Conventions: TEXT primary keys generated by lib/ids.js (prefix_random),
-- timestamps are ISO-8601 UTC strings, booleans are INTEGER 0/1,
-- JSON columns are TEXT validated by the application.

PRAGMA foreign_keys = ON;

-- ---------------------------------------------------------------- accounts

CREATE TABLE clients (
  id             TEXT PRIMARY KEY,
  name           TEXT NOT NULL,
  legal_name     TEXT,
  document       TEXT,
  contact_name   TEXT,
  contact_email  TEXT,
  contact_phone  TEXT,
  status         TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','paused','archived')),
  internal_notes TEXT,
  created_by     TEXT,
  created_at     TEXT NOT NULL,
  updated_at     TEXT NOT NULL
);

CREATE TABLE users (
  id            TEXT PRIMARY KEY,
  email         TEXT NOT NULL UNIQUE COLLATE NOCASE,
  name          TEXT NOT NULL,
  role          TEXT NOT NULL CHECK (role IN ('admin','manager','designer','finance','client')),
  client_id     TEXT REFERENCES clients(id) ON DELETE CASCADE,
  password_hash TEXT,
  status        TEXT NOT NULL DEFAULT 'invited' CHECK (status IN ('invited','active','disabled')),
  job_title     TEXT,
  phone         TEXT,
  notify_email  INTEGER NOT NULL DEFAULT 1,
  created_by    TEXT,
  created_at    TEXT NOT NULL,
  updated_at    TEXT NOT NULL,
  last_login_at TEXT,
  CHECK ((role = 'client') = (client_id IS NOT NULL))
);
CREATE INDEX users_client ON users(client_id);

CREATE TABLE sessions (
  id           TEXT PRIMARY KEY,
  token_hash   TEXT NOT NULL UNIQUE,
  user_id      TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at   TEXT NOT NULL,
  last_seen_at TEXT NOT NULL,
  expires_at   TEXT NOT NULL,
  revoked_at   TEXT,
  ip           TEXT,
  user_agent   TEXT
);
CREATE INDEX sessions_user ON sessions(user_id);

-- One-time tokens for invitations and password resets (only the hash is stored).
CREATE TABLE auth_tokens (
  token_hash TEXT PRIMARY KEY,
  user_id    TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  purpose    TEXT NOT NULL CHECK (purpose IN ('invite','reset')),
  created_by TEXT,
  created_at TEXT NOT NULL,
  expires_at TEXT NOT NULL,
  used_at    TEXT
);
CREATE INDEX auth_tokens_user ON auth_tokens(user_id);

CREATE TABLE login_attempts (
  id         INTEGER PRIMARY KEY AUTOINCREMENT,
  email      TEXT NOT NULL COLLATE NOCASE,
  ip         TEXT,
  success    INTEGER NOT NULL,
  created_at TEXT NOT NULL
);
CREATE INDEX login_attempts_lookup ON login_attempts(email, created_at);

-- Managers (and optionally other staff) see only the clients listed here.
CREATE TABLE staff_client_access (
  user_id    TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  client_id  TEXT NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
  granted_by TEXT,
  granted_at TEXT NOT NULL,
  PRIMARY KEY (user_id, client_id)
);

CREATE TABLE brands (
  id                    TEXT PRIMARY KEY,
  client_id             TEXT NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
  name                  TEXT NOT NULL,
  slug                  TEXT NOT NULL,
  description           TEXT,
  usage_guidelines      TEXT,
  typography_guidelines TEXT,
  internal_notes        TEXT,
  status                TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','archived')),
  created_by            TEXT,
  created_at            TEXT NOT NULL,
  updated_at            TEXT NOT NULL,
  UNIQUE (client_id, slug)
);
CREATE INDEX brands_client ON brands(client_id);

-- ------------------------------------------------------ catalog & commerce

CREATE TABLE services (
  id                 TEXT PRIMARY KEY,
  name               TEXT NOT NULL,
  kind               TEXT NOT NULL CHECK (kind IN ('subscription','one_off')),
  price_cents        INTEGER NOT NULL CHECK (price_cents >= 0),
  billing_interval   TEXT CHECK (billing_interval IN ('monthly')),
  description        TEXT,
  items              TEXT NOT NULL DEFAULT '[]',
  includes_editables INTEGER NOT NULL DEFAULT 0,
  active             INTEGER NOT NULL DEFAULT 1,
  sort_order         INTEGER NOT NULL DEFAULT 0,
  created_at         TEXT NOT NULL,
  updated_at         TEXT NOT NULL
);

CREATE TABLE subscriptions (
  id                 TEXT PRIMARY KEY,
  client_id          TEXT NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
  service_id         TEXT NOT NULL REFERENCES services(id),
  amount_cents       INTEGER NOT NULL CHECK (amount_cents >= 0),
  status             TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','active','paused','cancelled','failed')),
  payer_email        TEXT,
  external_reference TEXT NOT NULL UNIQUE,
  mp_preapproval_id  TEXT UNIQUE,
  checkout_url       TEXT,
  started_at         TEXT,
  next_billing_date  TEXT,
  cancelled_at       TEXT,
  failure_reason     TEXT,
  created_by         TEXT,
  created_at         TEXT NOT NULL,
  updated_at         TEXT NOT NULL
);
CREATE INDEX subscriptions_client ON subscriptions(client_id);

CREATE TABLE orders (
  id                 TEXT PRIMARY KEY,
  client_id          TEXT NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
  brand_id           TEXT REFERENCES brands(id) ON DELETE SET NULL,
  service_id         TEXT REFERENCES services(id),
  description        TEXT NOT NULL,
  amount_cents       INTEGER NOT NULL CHECK (amount_cents > 0),
  status             TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','pending_payment','paid','failed','cancelled','refunded')),
  due_date           TEXT,
  external_reference TEXT NOT NULL UNIQUE,
  mp_preference_id   TEXT,
  checkout_url       TEXT,
  paid_at            TEXT,
  failure_reason     TEXT,
  created_by         TEXT,
  created_at         TEXT NOT NULL,
  updated_at         TEXT NOT NULL
);
CREATE INDEX orders_client ON orders(client_id);

CREATE TABLE payments (
  id                  TEXT PRIMARY KEY,
  provider            TEXT NOT NULL DEFAULT 'mercadopago',
  provider_payment_id TEXT NOT NULL,
  order_id            TEXT REFERENCES orders(id) ON DELETE SET NULL,
  subscription_id     TEXT REFERENCES subscriptions(id) ON DELETE SET NULL,
  client_id           TEXT REFERENCES clients(id) ON DELETE SET NULL,
  status              TEXT NOT NULL,
  status_detail       TEXT,
  amount_cents        INTEGER,
  method              TEXT,
  paid_at             TEXT,
  raw                 TEXT,
  created_at          TEXT NOT NULL,
  updated_at          TEXT NOT NULL,
  UNIQUE (provider, provider_payment_id)
);

CREATE TABLE webhook_events (
  id              TEXT PRIMARY KEY,
  provider        TEXT NOT NULL,
  request_id      TEXT,
  topic           TEXT,
  resource_id     TEXT,
  signature_valid INTEGER NOT NULL,
  payload         TEXT,
  received_at     TEXT NOT NULL,
  processed_at    TEXT,
  error           TEXT,
  UNIQUE (provider, request_id)
);

-- ------------------------------------------------------- projects & tasks

CREATE TABLE projects (
  id                 TEXT PRIMARY KEY,
  brand_id           TEXT NOT NULL REFERENCES brands(id) ON DELETE CASCADE,
  service_id         TEXT REFERENCES services(id),
  subscription_id    TEXT REFERENCES subscriptions(id) ON DELETE SET NULL,
  name               TEXT NOT NULL,
  description        TEXT,
  status             TEXT NOT NULL DEFAULT 'planning' CHECK (status IN ('planning','in_progress','in_review','delivered','paused','archived')),
  includes_editables INTEGER NOT NULL DEFAULT 0,
  start_date         TEXT,
  due_date           TEXT,
  delivered_at       TEXT,
  internal_notes     TEXT,
  created_by         TEXT,
  created_at         TEXT NOT NULL,
  updated_at         TEXT NOT NULL
);
CREATE INDEX projects_brand ON projects(brand_id);

CREATE TABLE project_members (
  project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  user_id    TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  role       TEXT NOT NULL DEFAULT 'designer' CHECK (role IN ('lead','designer','editor')),
  added_by   TEXT,
  added_at   TEXT NOT NULL,
  PRIMARY KEY (project_id, user_id)
);
CREATE INDEX project_members_user ON project_members(user_id);

CREATE TABLE tasks (
  id           TEXT PRIMARY KEY,
  project_id   TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  material_id  TEXT REFERENCES materials(id) ON DELETE SET NULL,
  title        TEXT NOT NULL,
  description  TEXT,
  assignee_id  TEXT REFERENCES users(id) ON DELETE SET NULL,
  status       TEXT NOT NULL DEFAULT 'todo' CHECK (status IN ('todo','doing','review','done')),
  due_date     TEXT,
  sort_order   INTEGER NOT NULL DEFAULT 0,
  created_by   TEXT,
  created_at   TEXT NOT NULL,
  updated_at   TEXT NOT NULL,
  completed_at TEXT
);
CREATE INDEX tasks_project ON tasks(project_id);
CREATE INDEX tasks_assignee ON tasks(assignee_id);

CREATE TABLE campaigns (
  id          TEXT PRIMARY KEY,
  brand_id    TEXT NOT NULL REFERENCES brands(id) ON DELETE CASCADE,
  project_id  TEXT REFERENCES projects(id) ON DELETE SET NULL,
  name        TEXT NOT NULL,
  description TEXT,
  start_date  TEXT,
  end_date    TEXT,
  created_by  TEXT,
  created_at  TEXT NOT NULL,
  updated_at  TEXT NOT NULL
);
CREATE INDEX campaigns_brand ON campaigns(brand_id);

-- ------------------------------------------------------------- materials

-- area drives the first ZIP folder: identity -> "Identidade visual",
-- content -> "Conteúdo", other -> "Materiais". folder is the second level.
CREATE TABLE categories (
  id         TEXT PRIMARY KEY,
  slug       TEXT NOT NULL UNIQUE,
  name       TEXT NOT NULL,
  area       TEXT NOT NULL CHECK (area IN ('identity','content','other')),
  folder     TEXT NOT NULL,
  sort_order INTEGER NOT NULL DEFAULT 0,
  is_system  INTEGER NOT NULL DEFAULT 0,
  archived_at TEXT,
  created_by TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

-- Files a staff member uploaded but has not attached to a material yet.
-- Always private to the uploader (and admins).
CREATE TABLE uploads (
  id            TEXT PRIMARY KEY,
  user_id       TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  original_name TEXT NOT NULL,
  ext           TEXT NOT NULL,
  mime          TEXT NOT NULL,
  size_bytes    INTEGER NOT NULL,
  sha256        TEXT NOT NULL,
  storage_key   TEXT NOT NULL,
  media_kind    TEXT NOT NULL,
  width         INTEGER,
  height        INTEGER,
  duration_ms   INTEGER,
  status        TEXT NOT NULL DEFAULT 'uploaded' CHECK (status IN ('uploaded','attached','discarded')),
  created_at    TEXT NOT NULL,
  attached_at   TEXT
);
CREATE INDEX uploads_user ON uploads(user_id, status);

-- A material is either a delivered asset (logo, manual, presentation…) or a
-- content post (kind = 'post', with a post_details row). visibility controls
-- what the client can see; approval is tracked per version.
CREATE TABLE materials (
  id                  TEXT PRIMARY KEY,
  kind                TEXT NOT NULL CHECK (kind IN ('asset','post')),
  brand_id            TEXT NOT NULL REFERENCES brands(id) ON DELETE CASCADE,
  project_id          TEXT REFERENCES projects(id) ON DELETE SET NULL,
  category_id         TEXT NOT NULL REFERENCES categories(id),
  title               TEXT NOT NULL,
  description         TEXT,
  tags                TEXT NOT NULL DEFAULT '[]',
  owner_id            TEXT REFERENCES users(id) ON DELETE SET NULL,
  variant             TEXT CHECK (variant IS NULL OR variant IN ('principal','secundaria','simbolo','clara','escura','monocromatica')),
  preview_bg          TEXT NOT NULL DEFAULT 'auto' CHECK (preview_bg IN ('auto','light','dark','checker')),
  is_primary          INTEGER NOT NULL DEFAULT 0,
  sort_order          INTEGER NOT NULL DEFAULT 0,
  visibility          TEXT NOT NULL DEFAULT 'draft' CHECK (visibility IN ('draft','internal_review','released')),
  download_enabled    INTEGER NOT NULL DEFAULT 1,
  editable_included   INTEGER NOT NULL DEFAULT 0,
  requires_approval   INTEGER NOT NULL DEFAULT 1,
  approval_status     TEXT NOT NULL DEFAULT 'none' CHECK (approval_status IN ('none','pending','changes_requested','approved')),
  current_version_id  TEXT,
  released_version_id TEXT,
  approved_version_id TEXT,
  due_date            TEXT,
  internal_notes      TEXT,
  released_at         TEXT,
  released_by         TEXT,
  delivered_at        TEXT,
  archived_at         TEXT,
  archived_by         TEXT,
  created_by          TEXT,
  created_at          TEXT NOT NULL,
  updated_at          TEXT NOT NULL
);
CREATE INDEX materials_brand ON materials(brand_id, category_id);
CREATE INDEX materials_project ON materials(project_id);
CREATE INDEX materials_visibility ON materials(visibility, approval_status);
CREATE UNIQUE INDEX materials_one_primary
  ON materials(brand_id, category_id, COALESCE(variant, ''))
  WHERE is_primary = 1 AND archived_at IS NULL;

CREATE TABLE post_details (
  material_id        TEXT PRIMARY KEY REFERENCES materials(id) ON DELETE CASCADE,
  campaign_id        TEXT REFERENCES campaigns(id) ON DELETE SET NULL,
  network            TEXT NOT NULL CHECK (network IN ('instagram','facebook','linkedin','tiktok','youtube','x','pinterest','whatsapp','outro')),
  format             TEXT NOT NULL CHECK (format IN ('estatico','carrossel','stories','reels','video','outro')),
  planned_date       TEXT,
  planned_time       TEXT,
  publication_status TEXT NOT NULL DEFAULT 'not_scheduled' CHECK (publication_status IN ('not_scheduled','scheduled','published')),
  scheduled_at       TEXT,
  scheduled_by       TEXT,
  published_at       TEXT,
  published_by       TEXT,
  published_url      TEXT
);
CREATE INDEX post_details_date ON post_details(planned_date);

CREATE TABLE material_versions (
  id             TEXT PRIMARY KEY,
  material_id    TEXT NOT NULL REFERENCES materials(id) ON DELETE CASCADE,
  number         INTEGER NOT NULL,
  status         TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','internal_review','released','changes_requested','approved','superseded')),
  caption        TEXT,
  hashtags       TEXT,
  notes          TEXT,
  change_summary TEXT,
  created_by     TEXT NOT NULL REFERENCES users(id),
  created_at     TEXT NOT NULL,
  submitted_at   TEXT,
  released_at    TEXT,
  released_by    TEXT,
  decided_at     TEXT,
  decided_by     TEXT,
  UNIQUE (material_id, number)
);

-- role: original = full-quality presented file; final = approved delivery
-- export; editable = source file (only when the service includes it);
-- cover = poster/cover image used as thumbnail (never offered as a download
-- on its own). position orders carousel slides (1..n).
CREATE TABLE material_files (
  id                 TEXT PRIMARY KEY,
  version_id         TEXT NOT NULL REFERENCES material_versions(id) ON DELETE CASCADE,
  material_id        TEXT NOT NULL REFERENCES materials(id) ON DELETE CASCADE,
  role               TEXT NOT NULL CHECK (role IN ('original','final','editable','cover')),
  position           INTEGER NOT NULL DEFAULT 1,
  original_name      TEXT NOT NULL,
  display_name       TEXT NOT NULL,
  ext                TEXT NOT NULL,
  mime               TEXT NOT NULL,
  size_bytes         INTEGER NOT NULL,
  sha256             TEXT NOT NULL,
  storage_key        TEXT NOT NULL,
  media_kind         TEXT NOT NULL CHECK (media_kind IN ('image','vector','video','audio','pdf','font','document','archive','design','other')),
  width              INTEGER,
  height             INTEGER,
  duration_ms        INTEGER,
  preview_status     TEXT NOT NULL DEFAULT 'pending' CHECK (preview_status IN ('pending','ready','unsupported','failed')),
  font_distributable INTEGER,
  created_by         TEXT,
  created_at         TEXT NOT NULL
);
CREATE INDEX material_files_version ON material_files(version_id, role, position);
CREATE INDEX material_files_material ON material_files(material_id);

-- Optimised previews, generated separately from the originals.
CREATE TABLE file_renditions (
  file_id     TEXT NOT NULL REFERENCES material_files(id) ON DELETE CASCADE,
  kind        TEXT NOT NULL CHECK (kind IN ('thumb','preview','poster')),
  storage_key TEXT NOT NULL,
  mime        TEXT NOT NULL,
  width       INTEGER,
  height      INTEGER,
  size_bytes  INTEGER,
  created_at  TEXT NOT NULL,
  PRIMARY KEY (file_id, kind)
);

CREATE TABLE brand_colors (
  id         TEXT PRIMARY KEY,
  brand_id   TEXT NOT NULL REFERENCES brands(id) ON DELETE CASCADE,
  name       TEXT NOT NULL,
  hex        TEXT NOT NULL,
  rgb        TEXT,
  cmyk       TEXT,
  pantone    TEXT,
  role       TEXT,
  usage      TEXT,
  sort_order INTEGER NOT NULL DEFAULT 0,
  visibility TEXT NOT NULL DEFAULT 'draft' CHECK (visibility IN ('draft','released')),
  created_by TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);
CREATE INDEX brand_colors_brand ON brand_colors(brand_id);

-- distribution = 'allowed' lets clients download the font files attached
-- through material_id; 'reference_only' shows only the official source link.
CREATE TABLE brand_fonts (
  id           TEXT PRIMARY KEY,
  brand_id     TEXT NOT NULL REFERENCES brands(id) ON DELETE CASCADE,
  family       TEXT NOT NULL,
  role         TEXT,
  weights      TEXT,
  usage        TEXT,
  source_url   TEXT,
  license      TEXT,
  distribution TEXT NOT NULL DEFAULT 'reference_only' CHECK (distribution IN ('allowed','reference_only')),
  material_id  TEXT REFERENCES materials(id) ON DELETE SET NULL,
  sort_order   INTEGER NOT NULL DEFAULT 0,
  visibility   TEXT NOT NULL DEFAULT 'draft' CHECK (visibility IN ('draft','released')),
  created_by   TEXT,
  created_at   TEXT NOT NULL,
  updated_at   TEXT NOT NULL
);
CREATE INDEX brand_fonts_brand ON brand_fonts(brand_id);

CREATE TABLE kits (
  id          TEXT PRIMARY KEY,
  brand_id    TEXT NOT NULL REFERENCES brands(id) ON DELETE CASCADE,
  project_id  TEXT REFERENCES projects(id) ON DELETE SET NULL,
  name        TEXT NOT NULL,
  description TEXT,
  kind        TEXT NOT NULL DEFAULT 'custom' CHECK (kind IN ('brand_kit','project_package','custom')),
  status      TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','released','archived')),
  released_at TEXT,
  released_by TEXT,
  created_by  TEXT,
  created_at  TEXT NOT NULL,
  updated_at  TEXT NOT NULL
);
CREATE INDEX kits_brand ON kits(brand_id);

CREATE TABLE kit_items (
  kit_id      TEXT NOT NULL REFERENCES kits(id) ON DELETE CASCADE,
  material_id TEXT NOT NULL REFERENCES materials(id) ON DELETE CASCADE,
  sort_order  INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (kit_id, material_id)
);

-- --------------------------------------------------- review & approvals

CREATE TABLE comments (
  id             TEXT PRIMARY KEY,
  material_id    TEXT NOT NULL REFERENCES materials(id) ON DELETE CASCADE,
  version_id     TEXT REFERENCES material_versions(id) ON DELETE SET NULL,
  parent_id      TEXT REFERENCES comments(id) ON DELETE SET NULL,
  author_id      TEXT NOT NULL REFERENCES users(id),
  body           TEXT NOT NULL,
  visibility     TEXT NOT NULL CHECK (visibility IN ('client','internal')),
  kind           TEXT NOT NULL DEFAULT 'comment' CHECK (kind IN ('comment','change_request','approval_note')),
  slide_position INTEGER,
  created_at     TEXT NOT NULL,
  edited_at      TEXT,
  resolved_at    TEXT,
  resolved_by    TEXT
);
CREATE INDEX comments_material ON comments(material_id, created_at);

-- Immutable decision log. A new version always requires a new decision.
CREATE TABLE approvals (
  id          TEXT PRIMARY KEY,
  material_id TEXT NOT NULL REFERENCES materials(id) ON DELETE CASCADE,
  version_id  TEXT NOT NULL REFERENCES material_versions(id) ON DELETE CASCADE,
  decision    TEXT NOT NULL CHECK (decision IN ('approved','changes_requested')),
  user_id     TEXT NOT NULL REFERENCES users(id),
  comment_id  TEXT REFERENCES comments(id) ON DELETE SET NULL,
  ip          TEXT,
  user_agent  TEXT,
  created_at  TEXT NOT NULL
);
CREATE INDEX approvals_material ON approvals(material_id, created_at);

-- ------------------------------------------------------ delivery & downloads

CREATE TABLE releases (
  id           TEXT PRIMARY KEY,
  client_id    TEXT NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
  brand_id     TEXT NOT NULL REFERENCES brands(id) ON DELETE CASCADE,
  kit_id       TEXT REFERENCES kits(id) ON DELETE SET NULL,
  actor_id     TEXT NOT NULL REFERENCES users(id),
  message      TEXT,
  notify_email INTEGER NOT NULL DEFAULT 0,
  notify_app   INTEGER NOT NULL DEFAULT 1,
  created_at   TEXT NOT NULL
);
CREATE INDEX releases_client ON releases(client_id, created_at);

CREATE TABLE release_items (
  release_id       TEXT NOT NULL REFERENCES releases(id) ON DELETE CASCADE,
  material_id      TEXT NOT NULL REFERENCES materials(id) ON DELETE CASCADE,
  version_id       TEXT NOT NULL REFERENCES material_versions(id) ON DELETE CASCADE,
  download_enabled INTEGER NOT NULL,
  PRIMARY KEY (release_id, material_id)
);

CREATE TABLE zip_jobs (
  id              TEXT PRIMARY KEY,
  user_id         TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  client_id       TEXT REFERENCES clients(id) ON DELETE CASCADE,
  brand_id        TEXT REFERENCES brands(id) ON DELETE CASCADE,
  scope           TEXT NOT NULL,
  label           TEXT NOT NULL,
  filename        TEXT NOT NULL,
  status          TEXT NOT NULL DEFAULT 'queued' CHECK (status IN ('queued','running','ready','failed','expired')),
  file_count      INTEGER NOT NULL DEFAULT 0,
  total_bytes     INTEGER NOT NULL DEFAULT 0,
  processed_bytes INTEGER NOT NULL DEFAULT 0,
  storage_key     TEXT,
  size_bytes      INTEGER,
  error           TEXT,
  created_at      TEXT NOT NULL,
  started_at      TEXT,
  finished_at     TEXT,
  expires_at      TEXT
);
CREATE INDEX zip_jobs_user ON zip_jobs(user_id, created_at);

-- Download history. Never used to infer approval.
CREATE TABLE download_events (
  id          TEXT PRIMARY KEY,
  user_id     TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  client_id   TEXT REFERENCES clients(id) ON DELETE CASCADE,
  brand_id    TEXT REFERENCES brands(id) ON DELETE SET NULL,
  material_id TEXT REFERENCES materials(id) ON DELETE SET NULL,
  version_id  TEXT REFERENCES material_versions(id) ON DELETE SET NULL,
  file_id     TEXT REFERENCES material_files(id) ON DELETE SET NULL,
  zip_job_id  TEXT REFERENCES zip_jobs(id) ON DELETE SET NULL,
  kind        TEXT NOT NULL CHECK (kind IN ('file','zip')),
  scope       TEXT NOT NULL,
  ip          TEXT,
  user_agent  TEXT,
  created_at  TEXT NOT NULL
);
CREATE INDEX download_events_client ON download_events(client_id, created_at);
CREATE INDEX download_events_material ON download_events(material_id);

-- --------------------------------------------------------------- briefings

CREATE TABLE briefings (
  id           TEXT PRIMARY KEY,
  brand_id     TEXT NOT NULL REFERENCES brands(id) ON DELETE CASCADE,
  project_id   TEXT REFERENCES projects(id) ON DELETE SET NULL,
  title        TEXT NOT NULL,
  intro        TEXT,
  questions    TEXT NOT NULL DEFAULT '[]',
  answers      TEXT NOT NULL DEFAULT '{}',
  status       TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','awaiting_client','in_progress','submitted','reviewed')),
  due_date     TEXT,
  sent_at      TEXT,
  submitted_at TEXT,
  submitted_by TEXT,
  reviewed_at  TEXT,
  reviewed_by  TEXT,
  created_by   TEXT,
  created_at   TEXT NOT NULL,
  updated_at   TEXT NOT NULL
);
CREATE INDEX briefings_brand ON briefings(brand_id, status);

-- ------------------------------------------------ notifications & history

CREATE TABLE notifications (
  id          TEXT PRIMARY KEY,
  user_id     TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  type        TEXT NOT NULL,
  title       TEXT NOT NULL,
  body        TEXT,
  link        TEXT,
  entity_type TEXT,
  entity_id   TEXT,
  read_at     TEXT,
  created_at  TEXT NOT NULL
);
CREATE INDEX notifications_user ON notifications(user_id, read_at, created_at);

CREATE TABLE email_outbox (
  id          TEXT PRIMARY KEY,
  to_email    TEXT NOT NULL,
  to_user_id  TEXT REFERENCES users(id) ON DELETE SET NULL,
  subject     TEXT NOT NULL,
  text_body   TEXT NOT NULL,
  html_body   TEXT,
  status      TEXT NOT NULL DEFAULT 'queued' CHECK (status IN ('queued','sent','failed','not_configured')),
  error       TEXT,
  attempts    INTEGER NOT NULL DEFAULT 0,
  created_at  TEXT NOT NULL,
  sent_at     TEXT
);

-- Full audit trail. visibility = 'client' entries may be shown to the
-- client's own users; everything else is staff-only.
CREATE TABLE activity_log (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  actor_id    TEXT,
  actor_role  TEXT,
  action      TEXT NOT NULL,
  entity_type TEXT NOT NULL,
  entity_id   TEXT,
  client_id   TEXT,
  brand_id    TEXT,
  project_id  TEXT,
  material_id TEXT,
  summary     TEXT NOT NULL,
  data        TEXT,
  visibility  TEXT NOT NULL DEFAULT 'internal' CHECK (visibility IN ('internal','client')),
  ip          TEXT,
  created_at  TEXT NOT NULL
);
CREATE INDEX activity_client ON activity_log(client_id, created_at);
CREATE INDEX activity_material ON activity_log(material_id, created_at);
CREATE INDEX activity_entity ON activity_log(entity_type, entity_id);

CREATE TABLE settings (
  key        TEXT PRIMARY KEY,
  value      TEXT,
  updated_by TEXT,
  updated_at TEXT NOT NULL
);
