-- Contracts signed through AssinaVelox when a client acquires a plan
-- (subscription) or a one-off service such as brand identity (order).
-- The PDF is generated by Metta from a versioned template; AssinaVelox
-- collects the electronic acceptance and returns the final PDF and the
-- evidence page, stored here in private storage.

CREATE TABLE contract_template_versions (
  id         TEXT PRIMARY KEY,
  kind       TEXT NOT NULL CHECK (kind IN ('subscription','one_off')),
  version    INTEGER NOT NULL,
  title      TEXT NOT NULL,
  body       TEXT NOT NULL,
  created_by TEXT,
  created_at TEXT NOT NULL,
  UNIQUE (kind, version)
);

CREATE TABLE contracts (
  id                     TEXT PRIMARY KEY,
  client_id              TEXT NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
  brand_id               TEXT REFERENCES brands(id) ON DELETE SET NULL,
  order_id               TEXT REFERENCES orders(id) ON DELETE SET NULL,
  subscription_id        TEXT REFERENCES subscriptions(id) ON DELETE SET NULL,
  kind                   TEXT NOT NULL CHECK (kind IN ('subscription','one_off')),
  template_version_id    TEXT REFERENCES contract_template_versions(id),
  title                  TEXT NOT NULL,
  -- draft (unused) · sending (steps running) · sent (waiting for signatures)
  -- · completed · refused · expired · canceled · failed (sending failed, can retry)
  status                 TEXT NOT NULL DEFAULT 'sending'
                           CHECK (status IN ('draft','sending','sent','completed','refused','expired','canceled','failed')),
  provider               TEXT NOT NULL DEFAULT 'assinavelox',
  envelope_id            TEXT UNIQUE,
  display_code           TEXT,
  verification_code      TEXT,
  provider_status_label  TEXT,
  signature_status       TEXT,
  signature_status_label TEXT,
  client_signer_name     TEXT NOT NULL,
  client_signer_email    TEXT NOT NULL,
  client_signer_user_id  TEXT REFERENCES users(id) ON DELETE SET NULL,
  client_recipient_id    TEXT,
  client_status          TEXT,
  client_signed_at       TEXT,
  metta_signer_name      TEXT NOT NULL,
  metta_signer_email     TEXT NOT NULL,
  metta_recipient_id     TEXT,
  metta_status           TEXT,
  metta_signed_at        TEXT,
  refusal_reason         TEXT,
  expires_in_days        INTEGER NOT NULL DEFAULT 15,
  -- generated PDF sent for signature, and the files returned at completion
  document_key           TEXT,
  document_sha256        TEXT,
  document_size          INTEGER,
  document_pages         INTEGER,
  signed_key             TEXT,
  signed_sha256          TEXT,
  signed_size            INTEGER,
  evidence_key           TEXT,
  evidence_size          INTEGER,
  -- variables used to render the template (snapshot) and progress markers
  data                   TEXT NOT NULL DEFAULT '{}',
  step                   TEXT,
  error                  TEXT,
  attempts               INTEGER NOT NULL DEFAULT 0,
  embed_sessions         TEXT NOT NULL DEFAULT '[]',
  sent_at                TEXT,
  expires_at             TEXT,
  completed_at           TEXT,
  refused_at             TEXT,
  expired_at             TEXT,
  canceled_at            TEXT,
  cancel_reason          TEXT,
  last_synced_at         TEXT,
  created_by             TEXT,
  created_at             TEXT NOT NULL,
  updated_at             TEXT NOT NULL
);
CREATE INDEX contracts_client ON contracts(client_id, created_at);
CREATE INDEX contracts_status ON contracts(status, last_synced_at);
CREATE INDEX contracts_order ON contracts(order_id);
CREATE INDEX contracts_subscription ON contracts(subscription_id);
-- One live contract per order or subscription (a refused/expired/canceled
-- contract can be replaced by a new one).
CREATE UNIQUE INDEX contracts_one_open_order
  ON contracts(order_id) WHERE order_id IS NOT NULL AND status IN ('sending','sent','completed','failed');
CREATE UNIQUE INDEX contracts_one_open_subscription
  ON contracts(subscription_id) WHERE subscription_id IS NOT NULL AND status IN ('sending','sent','completed','failed');
