-- Contracts signed through AssinaVelox when a client acquires a plan
-- (subscription) or a one-off service such as brand identity (order).
-- The PDF is generated by Metta from a versioned template; AssinaVelox
-- collects the electronic acceptance and returns the final PDF and the
-- evidence page, stored here in private storage.

CREATE TABLE contract_template_versions (
  id         VARCHAR(64) NOT NULL,
  kind       VARCHAR(32) NOT NULL CHECK (kind IN ('subscription','one_off')),
  version    INT NOT NULL,
  title      TEXT NOT NULL,
  body       MEDIUMTEXT NOT NULL,
  created_by VARCHAR(64),
  created_at VARCHAR(32) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY contract_template_versions_kind (kind, version)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

-- One live contract (sending, sent, completed or failed) per order or
-- subscription: services/contracts.js checks it inside the creating
-- transaction (MySQL has no partial unique index, and order_id keeps
-- ON DELETE SET NULL, which rules out an indexed generated column).
CREATE TABLE contracts (
  id                     VARCHAR(64) NOT NULL,
  client_id              VARCHAR(64) NOT NULL,
  brand_id               VARCHAR(64),
  order_id               VARCHAR(64),
  subscription_id        VARCHAR(64),
  kind                   VARCHAR(32) NOT NULL CHECK (kind IN ('subscription','one_off')),
  template_version_id    VARCHAR(64),
  title                  TEXT NOT NULL,
  -- draft (unused) · sending (steps running) · sent (waiting for signatures)
  -- · completed · refused · expired · canceled · failed (sending failed, can retry)
  status                 VARCHAR(32) NOT NULL DEFAULT 'sending'
                           CHECK (status IN ('draft','sending','sent','completed','refused','expired','canceled','failed')),
  provider               VARCHAR(64) NOT NULL DEFAULT 'assinavelox',
  envelope_id            VARCHAR(191),
  display_code           VARCHAR(64),
  verification_code      VARCHAR(64),
  provider_status_label  TEXT,
  signature_status       VARCHAR(64),
  signature_status_label TEXT,
  client_signer_name     TEXT NOT NULL,
  client_signer_email    VARCHAR(320) NOT NULL,
  client_signer_user_id  VARCHAR(64),
  client_recipient_id    VARCHAR(191),
  client_status          VARCHAR(32),
  client_signed_at       VARCHAR(32),
  metta_signer_name      TEXT NOT NULL,
  metta_signer_email     VARCHAR(320) NOT NULL,
  metta_recipient_id     VARCHAR(191),
  metta_status           VARCHAR(32),
  metta_signed_at        VARCHAR(32),
  refusal_reason         TEXT,
  expires_in_days        INT NOT NULL DEFAULT 15,
  -- generated PDF sent for signature, and the files returned at completion
  document_key           VARCHAR(255),
  document_sha256        VARCHAR(64),
  document_size          BIGINT,
  document_pages         INT,
  signed_key             VARCHAR(255),
  signed_sha256          VARCHAR(64),
  signed_size            BIGINT,
  evidence_key           VARCHAR(255),
  evidence_size          BIGINT,
  -- variables used to render the template (snapshot) and progress markers
  data                   MEDIUMTEXT NOT NULL DEFAULT ('{}'),
  step                   VARCHAR(64),
  error                  TEXT,
  attempts               INT NOT NULL DEFAULT 0,
  embed_sessions         MEDIUMTEXT NOT NULL DEFAULT ('[]'),
  sent_at                VARCHAR(32),
  expires_at             VARCHAR(32),
  completed_at           VARCHAR(32),
  refused_at             VARCHAR(32),
  expired_at             VARCHAR(32),
  canceled_at            VARCHAR(32),
  cancel_reason          TEXT,
  last_synced_at         VARCHAR(32),
  created_by             VARCHAR(64),
  created_at             VARCHAR(32) NOT NULL,
  updated_at             VARCHAR(32) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY contracts_envelope (envelope_id),
  KEY contracts_client (client_id, created_at),
  KEY contracts_status (status, last_synced_at),
  KEY contracts_order (order_id),
  KEY contracts_subscription (subscription_id),
  KEY contracts_brand (brand_id),
  KEY contracts_template (template_version_id),
  KEY contracts_signer_user (client_signer_user_id),
  CONSTRAINT contracts_client_fk FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE,
  CONSTRAINT contracts_brand_fk FOREIGN KEY (brand_id) REFERENCES brands(id) ON DELETE SET NULL,
  CONSTRAINT contracts_order_fk FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE SET NULL,
  CONSTRAINT contracts_subscription_fk FOREIGN KEY (subscription_id) REFERENCES subscriptions(id) ON DELETE SET NULL,
  CONSTRAINT contracts_template_fk FOREIGN KEY (template_version_id) REFERENCES contract_template_versions(id),
  CONSTRAINT contracts_signer_user_fk FOREIGN KEY (client_signer_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
